### ISSUE TITLE
Is it possible to obtain these files oneself?

### ISSUE THREAD

**Issue by DarthOrdo** [slicedlime/examples#10]
I have checked the .jar files for the latest versions of Minecraft and did not find any files to do with worldgen or dimensions in there. The game seems to create a 'vanilla' datapack with these settings but the source of this is not anywhere that can be easily seen (eg. inside version.jar/data). Is the vanilla worldgen implemented in code but converted to a datapack on starting the game or loading a world?

I'm wondering as it would be useful to have vanilla reference files for custom worldgen easily accessible in the game's files. This would fit with (I believe) every other datapack modifiable feature used in vanilla.

**Comment by misode** [comment]
No, these files or the code that exports them is not included in the vanilla jar. The reason is that it's still an experimental feature.

I wrote a [simple mod](https://gist.github.com/misode/fbf59de0068e2c02152e717cf0bd7ae7) that can export the same files (with some technical knowledge to build it).
